name: Destroy

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to remove AWS resources for?
        options:
          - staging
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
  
      - name: Terraform Init
        id: init
        run: terraform -chdir=infra/deploy init

      - name: Select Workspace
        run: terraform -chdir=infra/deploy workspace select ${{ github.event.inputs.environment }}

      - name: Terraform Destroy
        run: terraform -chdir=infra/deploy destroy -auto-approve
        
