name: Test and Lint

on:
  pull_request:
    branches: [prod, main]

jobs:
  python:
    name: Python
    runs-on: ubontu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Checkout"
        uses: actions/Checkout@v4
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Python flake8
        run: docker compose run --rm app sh -c "flake8"
